# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
# import sqlite3
# conn = sqlite3.connect('student.db')
# cursor =conn.cursor()
# cursor.execute('insert into user (id,name) values("学号")')
# cursor.execute('insert into student (id,name) values("姓名")')
# cursor.execute('insert into student (id,name) values("英语成绩")')
# cursor.execute('insert into student (id,name) values("Javac成绩")')
# cursor.execute('insert into student (id,name) values("Python成绩")')
import pymysql

# 打开数据库连接
db = pymysql.connect(host='localhost',
                     user='root',
                     password='15013227986',
                     database='py01')
cursor=db.cursor()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(732, 535)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(50, 70, 511, 301))
        self.treeWidget.setObjectName("treeWidget")





        self.delete = QtWidgets.QPushButton(self.centralwidget)
        self.delete.setGeometry(QtCore.QRect(590, 230, 91, 41))
        self.delete.setObjectName("delete")

        self.change = QtWidgets.QPushButton(self.centralwidget)
        self.change.setGeometry(QtCore.QRect(590, 160, 91, 41))
        self.change.setObjectName("change")

        self.add= QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(590, 90, 91, 41))
        self.add.setObjectName("add")

        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(590, 300, 91, 41))
        self.exit.setObjectName("exit")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 732, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "学生成绩管理系统"))
        # self.treeWidget.headerItem().setText(0, _translate("MainWindow", "学号"))
        # self.treeWidget.headerItem().setText(1, _translate("MainWindow", "姓名"))
        # self.treeWidget.headerItem().setText(2, _translate("MainWindow", "英语成绩"))
        # self.treeWidget.headerItem().setText(3, _translate("MainWindow", "Java成绩"))
        # self.treeWidget.headerItem().setText(4, _translate("MainWindow", "Python成绩"))



        self.delete.setText(_translate("MainWindow", "删除"))
        self.delete.clicked.connect(delete)
        self.change.setText(_translate("MainWindow", "修改"))
        self.change.clicked.connect(change)
        self.add.setText(_translate("MainWindow", "新增"))
        self.add.clicked.connect(add)
        self.exit.setText(_translate("MainWindow", "退出系统"))
        self.exit.clicked.connect(cexit)

        def __init__(self, parent=None):
            super(Ui_MainWindow, self).__init__(parent)
            self.initUI()

        def initUI(self):
            self.tbGrade.setRowCount(0)

            vhayout = QHBoxLayout()
            table = QTableWidget()

            cursor.execute("select * from student")
            result = cursor.fetchall()
            row = cursor.rowcount()
            vol = len(result[0])
            cursor.close()
            db.close()
            table.setRowCount(row)
            table.setColumnCount(vol)
            table.setHorizontalHeaderLabels(['学号', '姓名', '英语成绩', 'Java成绩', '英语成绩'])
            for i in range(row):
                for j in range(vol):
                    data = QTableWidgetItem(str(result[i][j]))
                    table.setItem(i, j, data)
            table.resizeColumnToContents()
            table.resizeRowsToContents()
            table.setAlternatingRowColors(True)
            vhayout.addWidget(table)
            self.setLayout(vhayout)

def delete():
    pass

def change():
    pass

def add():
    pass

def cexit():
    cursor.close()
    db.close()
    MainWindow.close()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui=Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())